'use client';

import { useState, DragEvent } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@repo/ui';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/Label';
import { useToast } from '@/components/ui/useToast';
import { Plus, Trash2, X, ArrowUp, ArrowDown, Star } from 'lucide-react';
import { getColorHex } from '@/lib/utils/color-mapper';

interface Category {
  id: string;
  name: string;
  slug: string;
}

interface ProductVariant {
  id?: string;
  name: string;
  sku: string;
  price: number;
  quantity: number;
  attributes: {
    size?: string;
    color?: string;
    [key: string]: any;
  };
}

interface Product {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  comparePrice?: number | null;
  costPrice?: number | null;
  sku: string;
  barcode?: string | null;
  quantity: number;
  images: string[];
  featured: boolean;
  published: boolean;
  brand?: string | null;
  tags?: string[];
  categoryId: string;
  variants?: ProductVariant[];
}

interface ProductFormProps {
  product?: Product;
  categories: Category[];
}

// Helper function to generate slug from Vietnamese text
function generateSlug(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD') // Normalize to decomposed form
    .replace(/[\u0300-\u036f]/g, '') // Remove diacritics
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .replace(/[^a-z0-9\s-]/g, '') // Remove special characters
    .trim()
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
    .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens
}

export function ProductForm({ product, categories }: ProductFormProps) {
  const router = useRouter();
  const { success: toastSuccess, error: toastError } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(!product);
  const [isUploading, setIsUploading] = useState(false);
  const [newImageUrl, setNewImageUrl] = useState('');

  type ColorGroup = {
    color: string;
    colorHex?: string; // Store hex from existing variant
    sizes: {
      size: string;
      sku: string;
      price: number;
      quantity: number;
      id?: string;
    }[];
  };

  const initialColorGroups: ColorGroup[] = (() => {
    const groups: Record<string, ColorGroup> = {};
    (product?.variants || []).forEach((v) => {
      const color = v.attributes?.color || '';
      const size = v.attributes?.size || '';
      const colorHex = (v.attributes as any)?.colorHex;
      if (!groups[color]) {
        groups[color] = { color, colorHex, sizes: [] };
      }
      // Keep the first valid colorHex found
      if (colorHex && colorHex !== '#CCCCCC' && !groups[color].colorHex) {
        groups[color].colorHex = colorHex;
      }
      groups[color].sizes.push({
        size,
        sku: v.sku,
        price: Number(v.price),
        quantity: v.quantity,
        id: v.id,
      });
    });
    return Object.values(groups);
  })();

  const [colorGroups, setColorGroups] = useState<ColorGroup[]>(initialColorGroups);
  const [newColor, setNewColor] = useState('');
  const [defaultPriceForColor, setDefaultPriceForColor] = useState('');
  const [defaultQuantityForColor, setDefaultQuantityForColor] = useState('');
  const [sizeInputs, setSizeInputs] = useState<Record<string, string>>({});
  const [batchPriceInputs, setBatchPriceInputs] = useState<Record<string, string>>({});
  const [batchQuantityInputs, setBatchQuantityInputs] = useState<Record<string, string>>({});
  const initialColorImages: Record<string, string[]> = (() => {
    const map: Record<string, string[]> = {};
    (product?.variants || []).forEach((v) => {
      const color = v.attributes?.color || '';
      if (!color) return;
      const imgs = Array.isArray((v.attributes as any)?.images)
        ? ((v.attributes as any).images as string[])
        : [];
      if (imgs.length) {
        map[color] = Array.from(new Set([...(map[color] || []), ...imgs]));
      }
    });
    return map;
  })();
  const [colorImages, setColorImages] = useState<Record<string, string[]>>(initialColorImages);
  const [colorUrlInputs, setColorUrlInputs] = useState<Record<string, string>>({});

  const [formData, setFormData] = useState({
    name: product?.name || '',
    slug: product?.slug || '',
    description: product?.description || '',
    price: product?.price ? Number(product.price) : 0,
    comparePrice: product?.comparePrice ? Number(product.comparePrice) : undefined,
    costPrice: product?.costPrice ? Number(product.costPrice) : undefined,
    sku: product?.sku || '',
    barcode: product?.barcode || '',
    quantity: product?.quantity || 0,
    images: product?.images || [],
    published: product?.published || false,
    brand: product?.brand || '',
    tags: product?.tags || [],
    categoryId: product?.categoryId || categories[0]?.id || '',
  });

  const [tagInput, setTagInput] = useState('');
  const [variants, setVariants] = useState<ProductVariant[]>([]); // kept for backward compatibility, not used in UI

  // Auto-generate slug from name when creating new product
  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newName = e.target.value;
    setFormData((prev) => {
      const newData = { ...prev, name: newName };
      // Only auto-generate slug if creating new product and slug hasn't been manually edited
      if (isSlugAutoGenerated && !product) {
        newData.slug = generateSlug(newName);
      }
      return newData;
    });
  };

  // Track manual slug edits
  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setIsSlugAutoGenerated(false);
    setFormData({ ...formData, slug: e.target.value });
  };

  const addColorGroup = () => {
    const value = newColor.trim();
    if (!value) return;
    if (colorGroups.some((g) => g.color === value)) {
      setNewColor('');
      return;
    }
    setColorGroups((prev) => [...prev, { color: value, sizes: [] }]);
    setNewColor('');
    setColorImages((prev) => ({ ...prev, [value]: prev[value] || [] }));
  };

  const removeColorGroup = (color: string) => {
    setColorGroups((prev) => prev.filter((g) => g.color !== color));
    setSizeInputs((prev) => {
      const next = { ...prev };
      delete next[color];
      return next;
    });
    setBatchPriceInputs((prev) => {
      const next = { ...prev };
      delete next[color];
      return next;
    });
    setBatchQuantityInputs((prev) => {
      const next = { ...prev };
      delete next[color];
      return next;
    });
    setColorImages((prev) => {
      const next = { ...prev };
      delete next[color];
      return next;
    });
  };

  const addSizeToColor = (color: string, sizeValue: string) => {
    const size = sizeValue.trim();
    if (!size) return;
    setColorGroups((prev) =>
      prev.map((g) => {
        if (g.color !== color) return g;
        if (g.sizes.some((s) => s.size === size)) return g;
        const price = defaultPriceForColor ? parseFloat(defaultPriceForColor) : formData.price;
        const quantity = defaultQuantityForColor ? parseInt(defaultQuantityForColor, 10) || 0 : 0;
        return {
          ...g,
          sizes: [
            ...g.sizes,
            {
              size,
              sku: '',
              price,
              quantity,
            },
          ],
        };
      })
    );
  };

  const removeSizeFromColor = (color: string, size: string) => {
    setColorGroups((prev) =>
      prev.map((g) =>
        g.color === color ? { ...g, sizes: g.sizes.filter((s) => s.size !== size) } : g
      )
    );
  };

  const updateSizeField = (
    color: string,
    size: string,
    field: 'sku' | 'price' | 'quantity' | 'size',
    value: string
  ) => {
    setColorGroups((prev) =>
      prev.map((g) => {
        if (g.color !== color) return g;
        return {
          ...g,
          sizes: g.sizes.map((s) => {
            if (s.size !== size) return s;
            if (field === 'price') {
              return { ...s, price: parseFloat(value) || 0 };
            }
            if (field === 'quantity') {
              return { ...s, quantity: parseInt(value, 10) || 0 };
            }
            if (field === 'size') {
              return { ...s, size: value };
            }
            return { ...s, [field]: value };
          }),
        };
      })
    );
  };

  const applyBatchPriceToColor = (color: string, value: string) => {
    const num = parseFloat(value);
    if (Number.isNaN(num)) return;
    setColorGroups((prev) =>
      prev.map((g) =>
        g.color === color
          ? { ...g, sizes: g.sizes.map((s) => ({ ...s, price: num })) }
          : g
      )
    );
  };

  const applyBatchQuantityToColor = (color: string, value: string) => {
    const num = parseInt(value || '0', 10);
    if (Number.isNaN(num)) return;
    setColorGroups((prev) =>
      prev.map((g) =>
        g.color === color
          ? { ...g, sizes: g.sizes.map((s) => ({ ...s, quantity: num })) }
          : g
      )
    );
  };

  const addImageFromUrl = () => {
    if (!newImageUrl.trim()) return;
    setFormData((prev) => ({
      ...prev,
      images: [...prev.images, newImageUrl.trim()],
    }));
    setNewImageUrl('');
  };

  const moveImage = (from: number, to: number) => {
    setFormData((prev) => {
      const images = [...prev.images];
      const [moved] = images.splice(from, 1);
      images.splice(to, 0, moved);
      return { ...prev, images };
    });
  };

  const setMainImage = (index: number) => {
    if (index === 0) return;
    moveImage(index, 0);
  };

  const removeImage = (index: number) => {
    setFormData((prev) => ({
      ...prev,
      images: prev.images.filter((_, i) => i !== index),
    }));
  };

  const uploadFiles = async (files: FileList | null) => {
    if (!files || files.length === 0) return;
    setIsUploading(true);
    try {
      const uploadedUrls: string[] = [];
      for (const file of Array.from(files)) {
        const form = new FormData();
        form.append('file', file);
        const res = await fetch('/api/admin/uploads', {
          method: 'POST',
          body: form,
        });
        const data = await res.json();
        if (!res.ok || !data?.success || !data.url) {
          throw new Error(data?.error || 'Upload thất bại');
        }
        uploadedUrls.push(data.url);
      }
      if (uploadedUrls.length > 0) {
        setFormData((prev) => ({
          ...prev,
          images: [...prev.images, ...uploadedUrls],
        }));
      }
      toastSuccess('Tải ảnh thành công');
    } catch (error: any) {
      console.error('Upload error:', error);
      toastError(error.message || 'Upload thất bại');
    } finally {
      setIsUploading(false);
    }
  };

  // Color images helpers
  const uploadColorImages = async (color: string, files: FileList | null) => {
    if (!files || files.length === 0) return;
    setIsUploading(true);
    try {
      const uploadedUrls: string[] = [];
      for (const file of Array.from(files)) {
        const form = new FormData();
        form.append('file', file);
        const res = await fetch('/api/admin/uploads', {
          method: 'POST',
          body: form,
        });
        const data = await res.json();
        if (!res.ok || !data?.success || !data.url) {
          throw new Error(data?.error || 'Upload thất bại');
        }
        uploadedUrls.push(data.url);
      }
      if (uploadedUrls.length > 0) {
        setColorImages((prev) => ({
          ...prev,
          [color]: [...(prev[color] || []), ...uploadedUrls],
        }));
      }
      toastSuccess('Tải ảnh thành công');
    } catch (error: any) {
      console.error('Upload error:', error);
      toastError(error.message || 'Upload thất bại');
    } finally {
      setIsUploading(false);
    }
  };

  const addColorImageFromUrl = (color: string, url: string) => {
    if (!url.trim()) return;
    setColorImages((prev) => ({
      ...prev,
      [color]: [...(prev[color] || []), url.trim()],
    }));
  };

  const moveColorImage = (color: string, from: number, to: number) => {
    setColorImages((prev) => {
      const imgs = [...(prev[color] || [])];
      const [moved] = imgs.splice(from, 1);
      imgs.splice(to, 0, moved);
      return { ...prev, [color]: imgs };
    });
  };

  const setColorMainImage = (color: string, index: number) => {
    if (index === 0) return;
    moveColorImage(color, index, 0);
  };

  const removeColorImage = (color: string, index: number) => {
    setColorImages((prev) => ({
      ...prev,
      [color]: (prev[color] || []).filter((_, i) => i !== index),
    }));
  };

  const handleDrop = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    if (isUploading) return;
    const files = e.dataTransfer.files;
    uploadFiles(files);
  };

  const handleDragOver = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
  };

  // Variant management functions (legacy placeholders)
  const addVariant = () => {};
  const removeVariant = (_index: number) => {};
  const updateVariant = (_index: number, _field: keyof ProductVariant, _value: any) => {};
  const updateVariantAttribute = (_index: number, _key: string, _value: string) => {};

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      // Client-side guard for required fields before calling API
      const missing: string[] = [];
      if (!formData.name.trim()) missing.push('Tên sản phẩm');
      if (!formData.slug.trim()) missing.push('Slug');
      if (!formData.description.trim()) missing.push('Mô tả');
      if (!formData.sku.trim()) missing.push('SKU');
      if (!formData.categoryId) missing.push('Danh mục');
      if (!formData.price || Number.isNaN(formData.price) || formData.price <= 0) {
        missing.push('Giá > 0');
      }

      // Validate variants input before hitting API
      const variantErrors: string[] = [];
      colorGroups.forEach((g) => {
        g.sizes.forEach((s) => {
          if (!s.sku.trim()) variantErrors.push(`SKU còn trống cho màu ${g.color}, size ${s.size}`);
          if (!s.price || Number.isNaN(s.price) || s.price <= 0) {
            variantErrors.push(`Giá phải > 0 cho màu ${g.color}, size ${s.size}`);
          }
          if (s.quantity < 0) {
            variantErrors.push(`Số lượng không âm cho màu ${g.color}, size ${s.size}`);
          }
        });
      });

      if (missing.length > 0 || variantErrors.length > 0) {
        const message = [...missing, ...variantErrors].join('\n');
        throw new Error(message || 'Vui lòng kiểm tra lại dữ liệu');
      }

      // Flatten colorGroups -> variants
      const flattenedVariants: ProductVariant[] = colorGroups.flatMap((g) =>
        g.sizes.map((s) => {
          // Use existing colorHex if available, otherwise get from mapper
          const colorHex = g.colorHex && g.colorHex !== '#CCCCCC' 
            ? g.colorHex 
            : getColorHex(g.color);
          const variantColorImages = colorImages[g.color] || [];
          return {
            name: `${s.size} ${g.color}`.trim() || 'Variant',
            sku: s.sku,
            price: s.price,
            quantity: s.quantity,
            attributes: { 
              size: s.size, 
              color: g.color,
              colorHex: colorHex,
              images: variantColorImages,
            },
          };
        })
      );

      // Validate variants: size+color combo not duplicated, and not both empty
      const combos = flattenedVariants.map((v) => {
        const size = v.attributes.size || '';
        const color = v.attributes.color || '';
        return { key: `${size}::${color}`, size, color };
      });
      const duplicateCombo = combos.find((combo, idx) => combos.findIndex(c => c.key === combo.key) !== idx);
      if (duplicateCombo) {
        throw new Error('Biến thể trùng nhau (size + màu). Vui lòng kiểm tra lại.');
      }
      const emptyCombo = combos.find((combo) => !combo.size && !combo.color);
      if (emptyCombo) {
        throw new Error('Mỗi biến thể cần ít nhất size hoặc màu.');
      }

      const url = product
        ? `/api/admin/products/${product.id}`
        : '/api/admin/products';
      const method = product ? 'PATCH' : 'POST';

      // Prepare variants data
      const variantsData = flattenedVariants.map((v) => ({
        name: v.name,
        sku: v.sku,
        price: v.price,
        quantity: v.quantity,
        attributes: v.attributes,
      }));

      const totalQuantity = variantsData.reduce((sum, v) => sum + (v.quantity || 0), 0);

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ...formData,
          quantity: totalQuantity,
          variants: variantsData.map((v) => ({
            ...v,
            attributes: {
              ...v.attributes,
              images: colorImages[v.attributes.color || ''] || [],
            },
          })),
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        const serverDetails =
          Array.isArray(data?.details) && data.details.length > 0
            ? data.details
                .map((d: any) => {
                  const path = Array.isArray(d?.path) ? d.path.join('.') : '';
                  const msg = d?.message || '';
                  return path ? `${path}: ${msg}` : msg;
                })
                .filter(Boolean)
                .join('\n')
            : '';
        const message = data?.error || serverDetails || 'lỗi khi tạo/cập nhật sản phẩm';
        console.warn('Product create/update failed', {
          status: response.status,
          message,
          details: data?.details,
        });
        throw new Error(message);
      }

      toastSuccess(product ? 'Sản phẩm đã được cập nhật' : 'Sản phẩm đã được tạo');
      router.push('/admin/products');
      router.refresh();
    } catch (error: any) {
      toastError(error.message || 'Có lỗi xảy ra');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="bg-white rounded-lg shadow p-6 space-y-6">
      {/* Basic Information */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold text-gray-900">Thông tin cơ bản</h2>
        
        <div>
          <Label htmlFor="name">Tên sản phẩm *</Label>
          <Input
            id="name"
            value={formData.name}
            onChange={handleNameChange}
            required
          />
        </div>

        <div>
          <div className="flex items-center justify-between mb-1">
            <Label htmlFor="slug">Slug *</Label>
            {!product && (
              <button
                type="button"
                onClick={() => {
                  setIsSlugAutoGenerated(true);
                  setFormData({ ...formData, slug: generateSlug(formData.name) });
                }}
                className="text-sm text-blue-600 hover:text-blue-700"
              >
                Tự động tạo từ tên
              </button>
            )}
          </div>
          <Input
            id="slug"
            value={formData.slug}
            onChange={handleSlugChange}
            required
            placeholder="slug-se-tu-dong-tao"
          />
          {!product && (
            <p className="mt-1 text-xs text-gray-500">
              Slug sẽ được tự động tạo từ tên sản phẩm. Bạn có thể chỉnh sửa thủ công nếu cần.
            </p>
          )}
        </div>

        <div>
          <Label htmlFor="description">Mô tả *</Label>
          <textarea
            id="description"
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            rows={4}
            required
          />
        </div>

        {/* Images */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="font-medium text-gray-900">Ảnh sản phẩm</h3>
            <span className="text-sm text-gray-500">Ảnh đầu tiên sẽ dùng làm ảnh chính</span>
          </div>

          <div
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            className="border-2 border-dashed border-gray-300 rounded-lg p-4 bg-gray-50"
          >
            <div className="flex flex-col sm:flex-row sm:items-center gap-3">
              <input
                type="file"
                accept="image/*"
                multiple
                onChange={(e) => uploadFiles(e.target.files)}
                disabled={isUploading}
              />
              <p className="text-sm text-gray-500">
                Kéo & thả hoặc chọn nhiều ảnh. Hỗ trợ sắp xếp/thay đổi ảnh chính.
              </p>
              {isUploading && (
                <span className="text-sm text-blue-600">Đang tải ảnh...</span>
              )}
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Input
              placeholder="Dán URL ảnh (tùy chọn)"
              value={newImageUrl}
              onChange={(e) => setNewImageUrl(e.target.value)}
            />
            <Button type="button" variant="outline" onClick={addImageFromUrl}>
              Thêm URL
            </Button>
          </div>

          {formData.images.length > 0 ? (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {formData.images.map((img, idx) => (
                <div
                  key={idx}
                  className="relative border border-gray-200 rounded-lg overflow-hidden bg-white shadow-sm"
                >
                  <img
                    src={img}
                    alt={`Image ${idx + 1}`}
                    className="w-full h-40 object-cover"
                  />
                  {idx === 0 && (
                    <div className="absolute top-2 left-2 inline-flex items-center gap-1 bg-blue-600 text-white text-xs px-2 py-1 rounded">
                      <Star className="w-3 h-3" /> Ảnh chính
                    </div>
                  )}
                  <div className="flex items-center justify-between px-2 py-2 bg-gray-50 border-t">
                    <div className="flex items-center gap-1">
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        disabled={idx === 0}
                        onClick={() => moveImage(idx, idx - 1)}
                      >
                        <ArrowUp className="w-4 h-4" />
                      </Button>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        disabled={idx === formData.images.length - 1}
                        onClick={() => moveImage(idx, idx + 1)}
                      >
                        <ArrowDown className="w-4 h-4" />
                      </Button>
                    </div>
                    <div className="flex items-center gap-1">
                      {idx !== 0 && (
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => setMainImage(idx)}
                        >
                          Đặt làm chính
                        </Button>
                      )}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => removeImage(idx)}
                        className="text-red-600 hover:text-red-700"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-sm text-gray-500">Chưa có ảnh. Thêm ảnh để hiển thị.</div>
          )}
        </div>

        <div>
          <Label htmlFor="categoryId">Danh mục *</Label>
          <select
            id="categoryId"
            value={formData.categoryId}
            onChange={(e) => setFormData({ ...formData, categoryId: e.target.value })}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            required
          >
            {categories.map((cat) => (
              <option key={cat.id} value={cat.id}>
                {cat.name}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Pricing */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold text-gray-900">Giá cả</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <Label htmlFor="price">Giá bán *</Label>
            <Input
              id="price"
              type="number"
              min="0"
              value={formData.price}
              onChange={(e) => setFormData({ ...formData, price: parseFloat(e.target.value) || 0 })}
              required
            />
          </div>
          <div>
            <Label htmlFor="comparePrice">Giá so sánh</Label>
            <Input
              id="comparePrice"
              type="number"
              step="0.01"
              min="0"
              value={formData.comparePrice || ''}
              onChange={(e) => setFormData({ ...formData, comparePrice: parseFloat(e.target.value) || undefined })}
            />
          </div>
          <div>
            <Label htmlFor="costPrice">Giá vốn</Label>
            <Input
              id="costPrice"
              type="number"
              step="0.01"
              min="0"
              value={formData.costPrice || ''}
              onChange={(e) => setFormData({ ...formData, costPrice: parseFloat(e.target.value) || undefined })}
            />
          </div>
        </div>
      </div>

      {/* Inventory */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold text-gray-900">Tồn kho</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <Label htmlFor="sku">SKU *</Label>
            <Input
              id="sku"
              value={formData.sku}
              onChange={(e) => setFormData({ ...formData, sku: e.target.value })}
              required
            />
          </div>
          <div>
            <Label htmlFor="barcode">Barcode</Label>
            <Input
              id="barcode"
              value={formData.barcode}
              onChange={(e) => setFormData({ ...formData, barcode: e.target.value })}
            />
          </div>
          <div className="flex flex-col justify-center">
            <span className="text-sm text-gray-600">Tổng tồn kho (tính từ biến thể)</span>
            <span className="text-lg font-semibold text-gray-900">
              {colorGroups.reduce((sum, g) => sum + g.sizes.reduce((s, v) => s + (v.quantity || 0), 0), 0)}
            </span>
          </div>
        </div>
      </div>

      {/* Variants by Color */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-gray-900">Biến thể sản phẩm (theo Màu)</h2>
          <div className="flex items-center gap-2">
            <Input
              value={newColor}
              onChange={(e) => setNewColor(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault();
                  addColorGroup();
                }
              }}
              placeholder="Nhập màu, ví dụ: Đen"
              className="w-40"
            />
            <Button type="button" variant="outline" onClick={addColorGroup}>
              Thêm màu
            </Button>
          </div>
        </div>

        {colorGroups.length === 0 ? (
          <div className="text-center py-8 border-2 border-dashed border-gray-300 rounded-lg">
            <p className="text-gray-500 mb-2">Chưa có biến thể nào</p>
            <p className="text-sm text-gray-400">
              Thêm màu, sau đó thêm size và SKU/giá/số lượng cho từng size.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {colorGroups.map((group) => (
              <div key={group.color} className="border border-gray-200 rounded-lg bg-gray-50 p-3 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className="text-base font-semibold text-gray-900">{group.color || 'Không màu'}</span>
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => removeColorGroup(group.color)}
                    className="text-red-600 hover:text-red-700 hover:bg-red-50"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  <div className="flex items-center gap-2">
                    <Input
                      type="number"
                      min="0"
                      step="0.01"
                      placeholder="Giá áp cho màu này"
                      value={batchPriceInputs[group.color] || ''}
                      onChange={(e) =>
                        setBatchPriceInputs((prev) => ({ ...prev, [group.color]: e.target.value }))
                      }
                    />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => applyBatchPriceToColor(group.color, batchPriceInputs[group.color] || '')}
                    >
                      Áp giá
                    </Button>
                  </div>
                  <div className="flex items-center gap-2">
                    <Input
                      type="number"
                      min="0"
                      placeholder="SL áp cho màu này"
                      value={batchQuantityInputs[group.color] || ''}
                      onChange={(e) =>
                        setBatchQuantityInputs((prev) => ({ ...prev, [group.color]: e.target.value }))
                      }
                    />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => applyBatchQuantityToColor(group.color, batchQuantityInputs[group.color] || '')}
                    >
                      Áp SL
                    </Button>
                  </div>
                  <div className="flex items-center gap-2">
                    <Input
                      placeholder="Thêm size cho màu này (VD: S)"
                      value={sizeInputs[group.color] || ''}
                      onChange={(e) =>
                        setSizeInputs((prev) => ({ ...prev, [group.color]: e.target.value }))
                      }
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') {
                          e.preventDefault();
                          addSizeToColor(group.color, sizeInputs[group.color] || '');
                          setSizeInputs((prev) => ({ ...prev, [group.color]: '' }));
                        }
                      }}
                    />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => {
                        addSizeToColor(group.color, sizeInputs[group.color] || '');
                        setSizeInputs((prev) => ({ ...prev, [group.color]: '' }));
                      }}
                    >
                      Thêm size
                    </Button>
                  </div>
                </div>

                {/* Color images */}
                <div className="space-y-2 rounded-md border border-gray-200 bg-white p-3">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-semibold text-gray-900">Ảnh cho màu này</span>
                    <span className="text-xs text-gray-500">Ảnh đầu tiên sẽ là ảnh chính của màu</span>
                  </div>
                  <div className="flex flex-col sm:flex-row sm:items-center gap-3">
                    <input
                      type="file"
                      accept="image/*"
                      multiple
                      onChange={(e) => uploadColorImages(group.color, e.target.files)}
                      disabled={isUploading}
                    />
                    <Input
                      placeholder="Dán URL ảnh cho màu này"
                      value={colorUrlInputs[group.color] || ''}
                      onChange={(e) =>
                        setColorUrlInputs((prev) => ({ ...prev, [group.color]: e.target.value }))
                      }
                    />
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => {
                        addColorImageFromUrl(group.color, colorUrlInputs[group.color] || '');
                        setColorUrlInputs((prev) => ({ ...prev, [group.color]: '' }));
                      }}
                    >
                      Thêm URL
                    </Button>
                  </div>
                  {(colorImages[group.color] || []).length > 0 ? (
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                      {(colorImages[group.color] || []).map((img, idx) => (
                        <div key={idx} className="relative border border-gray-200 rounded-lg overflow-hidden bg-gray-50">
                          <img src={img} alt={`Color ${group.color} ${idx + 1}`} className="w-full h-28 object-cover" />
                          {idx === 0 && (
                            <div className="absolute top-1 left-1 inline-flex items-center gap-1 bg-blue-600 text-white text-[11px] px-2 py-0.5 rounded">
                              <Star className="w-3 h-3" /> Chính
                            </div>
                          )}
                          <div className="flex items-center justify-between px-2 py-2 bg-white border-t">
                            <div className="flex items-center gap-1">
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                disabled={idx === 0}
                                onClick={() => moveColorImage(group.color, idx, idx - 1)}
                              >
                                <ArrowUp className="w-4 h-4" />
                              </Button>
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                disabled={idx === (colorImages[group.color]?.length || 1) - 1}
                                onClick={() => moveColorImage(group.color, idx, idx + 1)}
                              >
                                <ArrowDown className="w-4 h-4" />
                              </Button>
                            </div>
                            <div className="flex items-center gap-1">
                              {idx !== 0 && (
                                <Button
                                  type="button"
                                  variant="outline"
                                  size="sm"
                                  onClick={() => setColorMainImage(group.color, idx)}
                                >
                                  Đặt chính
                                </Button>
                              )}
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={() => removeColorImage(group.color, idx)}
                                className="text-red-600 hover:text-red-700"
                              >
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="text-sm text-gray-500">Chưa có ảnh cho màu này.</div>
                  )}
                </div>

                {group.sizes.length === 0 ? (
                  <div className="text-sm text-gray-500">Chưa có size cho màu này. Thêm size để nhập SKU/giá/SL.</div>
                ) : (
                  <div className="space-y-2">
                    <div className="hidden md:grid grid-cols-12 gap-3 text-xs font-semibold text-gray-600 px-2">
                      <span className="col-span-2">Size</span>
                      <span className="col-span-3">SKU *</span>
                      <span className="col-span-3">Giá *</span>
                      <span className="col-span-3">Số lượng *</span>
                      <span className="col-span-1 text-right">Xóa</span>
                    </div>
                    <div className="space-y-2">
                      {group.sizes.map((s) => (
                        <div
                          key={s.size}
                          className="grid grid-cols-1 md:grid-cols-12 gap-3 items-center border border-gray-200 rounded-lg p-3 bg-white"
                        >
                          <div className="md:col-span-2">
                            <Label className="md:hidden text-xs text-gray-500">Size</Label>
                            <Input
                              value={s.size}
                              onChange={(e) => updateSizeField(group.color, s.size, 'size', e.target.value)}
                              placeholder="VD: M"
                            />
                          </div>
                          <div className="md:col-span-3">
                            <Label className="md:hidden text-xs text-gray-500">SKU *</Label>
                            <Input
                              value={s.sku}
                              onChange={(e) => updateSizeField(group.color, s.size, 'sku', e.target.value)}
                              required
                              placeholder="SKU"
                            />
                          </div>
                          <div className="md:col-span-3">
                            <Label className="md:hidden text-xs text-gray-500">Giá *</Label>
                            <Input
                              type="number"
                              step="0.01"
                              min="0"
                              value={s.price}
                              onChange={(e) => updateSizeField(group.color, s.size, 'price', e.target.value)}
                              required
                            />
                          </div>
                          <div className="md:col-span-3">
                            <Label className="md:hidden text-xs text-gray-500">Số lượng *</Label>
                            <Input
                              type="number"
                              min="0"
                              value={s.quantity}
                              onChange={(e) => updateSizeField(group.color, s.size, 'quantity', e.target.value)}
                              required
                            />
                          </div>
                          <div className="md:col-span-1 flex justify-end">
                            <Button
                              type="button"
                              variant="outline"
                              onClick={() => removeSizeFromColor(group.color, s.size)}
                              className="text-red-600 hover:text-red-700 hover:bg-red-50"
                            >
                              <Trash2 className="w-4 h-4" />
                            </Button>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Brand & Tags */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold text-gray-900">Thương hiệu & Thẻ</h2>
        
        <div>
          <Label htmlFor="brand">Thương hiệu</Label>
          <Input
            id="brand"
            value={formData.brand}
            onChange={(e) => setFormData({ ...formData, brand: e.target.value })}
            placeholder="Nhập tên thương hiệu"
          />
        </div>

        <div>
          <Label htmlFor="tags">Thẻ sản phẩm</Label>
          <div className="space-y-2">
            <div className="flex gap-2">
              <Input
                id="tags"
                value={tagInput}
                onChange={(e) => setTagInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && tagInput.trim()) {
                    e.preventDefault();
                    if (!formData.tags.includes(tagInput.trim())) {
                      setFormData({
                        ...formData,
                        tags: [...formData.tags, tagInput.trim()],
                      });
                    }
                    setTagInput('');
                  }
                }}
                placeholder="Nhập thẻ và nhấn Enter"
              />
              <Button
                type="button"
                variant="outline"
                onClick={() => {
                  if (tagInput.trim() && !formData.tags.includes(tagInput.trim())) {
                    setFormData({
                      ...formData,
                      tags: [...formData.tags, tagInput.trim()],
                    });
                    setTagInput('');
                  }
                }}
              >
                Thêm
              </Button>
            </div>
            {formData.tags.length > 0 && (
              <div className="flex flex-wrap gap-2">
                {formData.tags.map((tag, index) => (
                  <span
                    key={index}
                    className="inline-flex items-center gap-1 px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm"
                  >
                    {tag}
                    <button
                      type="button"
                      onClick={() => {
                        setFormData({
                          ...formData,
                          tags: formData.tags.filter((_, i) => i !== index),
                        });
                      }}
                      className="ml-1 hover:text-blue-600"
                    >
                      ×
                    </button>
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Settings */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold text-gray-900">Cài đặt</h2>
        
        <div className="flex items-center space-x-6">
          <label className="flex items-center">
            <input
              type="checkbox"
              checked={formData.published}
              onChange={(e) => setFormData({ ...formData, published: e.target.checked })}
              className="mr-2"
            />
            <span>Xuất bản</span>
          </label>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end space-x-4 pt-4 border-t">
        <Button
          type="button"
          variant="outline"
          onClick={() => router.back()}
        >
          Hủy
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? 'Đang lưu...' : product ? 'Cập nhật' : 'Tạo sản phẩm'}
        </Button>
      </div>
    </form>
  );
}

